spring:
  application:
    name: CleVo
  config:
    import:
      - classpath:/yaml/application-dev.yml
      - classpath:/yaml/application-test.yml
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/